/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 14-Jun-2021 18:15:33
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 51
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2021a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int hpf_50_1kHz_length = 51;
const real32_T hpf_50_1kHz_coeffs[51] = {
  0.0004158202792,0.0003043449833,0.0001764718472,-1.158059422e-05,-0.0003094179265,
  -0.0007695821114,-0.001444278634,-0.002381902654, -0.00362356659,-0.005199837964,
   -0.00712789176,-0.009409262799, -0.01202835236, -0.01495180465, -0.01812882721,
   -0.02149245888, -0.02496176213, -0.02844483033,  -0.0318424888, -0.03505250067,
   -0.03797402605, -0.04051220044, -0.04258245602, -0.04411448166, -0.04505552724,
     0.9550995827, -0.04505552724, -0.04411448166, -0.04258245602, -0.04051220044,
   -0.03797402605, -0.03505250067,  -0.0318424888, -0.02844483033, -0.02496176213,
   -0.02149245888, -0.01812882721, -0.01495180465, -0.01202835236,-0.009409262799,
   -0.00712789176,-0.005199837964, -0.00362356659,-0.002381902654,-0.001444278634,
  -0.0007695821114,-0.0003094179265,-1.158059422e-05,0.0001764718472,0.0003043449833,
  0.0004158202792
};
