/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 20-Jun-2021 22:37:43
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 26
 * Stable            : Yes
 * Linear Phase      : Yes (Type 4)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2021a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int fir_hpf_length = 26;
const real32_T fir_hpf_1kHz_coeffs[26] = {
   0.001728184172,0.0007238018443,-0.001026390702,-0.003779287217,-0.007852439769,
   -0.01365482341, -0.02175555564, -0.03304109722, -0.04909909517, -0.07327919453,
    -0.1143176854,  -0.2044693679,  -0.6351770163,   0.6351770163,   0.2044693679,
     0.1143176854,  0.07327919453,  0.04909909517,  0.03304109722,  0.02175555564,
    0.01365482341, 0.007852439769, 0.003779287217, 0.001026390702,-0.0007238018443,
  -0.001728184172
};
