/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 20-Jun-2021 22:38:09
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 26
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2021a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int fir_lpf_length = 26;
const real32_T fir_lpf_1kHz_coeffs[26] = {
    0.01106905565,  0.01458931901,   0.0187117774,  0.02338849567,  0.02852285653,
    0.03396807611,  0.03953079507,  0.04498021305,  0.05006245896,  0.05451915786,
    0.05810841173,  0.06062588096,  0.06192350388,  0.06192350388,  0.06062588096,
    0.05810841173,  0.05451915786,  0.05006245896,  0.04498021305,  0.03953079507,
    0.03396807611,  0.02852285653,  0.02338849567,   0.0187117774,  0.01458931901,
    0.01106905565
};
