/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 14-Jun-2021 18:14:50
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 26
 * Stable            : Yes
 * Linear Phase      : Yes (Type 4)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2021a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int hpf_25_1kHz_length = 26;
const real32_T hpf_25_1kHz_coeffs[26] = {
  0.0004252025392,0.0001768884395,-0.000310306059,-0.001479151309,-0.003871652298,
  -0.008132642135, -0.01505001355, -0.02568551153,  -0.0417371206, -0.06658510864,
    -0.1089071631,  -0.2007880509,  -0.6330425143,   0.6330425143,   0.2007880509,
     0.1089071631,  0.06658510864,   0.0417371206,  0.02568551153,  0.01505001355,
   0.008132642135, 0.003871652298, 0.001479151309, 0.000310306059,-0.0001768884395,
  -0.0004252025392
};
