/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 14-Jun-2021 18:15:54
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 51
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2021a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int lpf_50_1kHz_length = 51;
const real32_T lpf_50_1kHz_coeffs[51] = {
  -0.0004628362367,-0.0003387566539,-0.0001964251715,1.288998919e-05,0.0003444032045,
  0.0008565972093, 0.001607580343, 0.002651219722,  0.00403327588, 0.005787773058,
   0.007933828048,   0.0104731489,  0.01338837389,  0.01664237492,  0.02017861791,
    0.02392256819,  0.02778413892,  0.03166102991,  0.03544285893,  0.03901581466,
    0.04226767272,   0.0450928323,  0.04739717022,  0.04910241812,  0.05014986917,
    0.05050312728,  0.05014986917,  0.04910241812,  0.04739717022,   0.0450928323,
    0.04226767272,  0.03901581466,  0.03544285893,  0.03166102991,  0.02778413892,
    0.02392256819,  0.02017861791,  0.01664237492,  0.01338837389,   0.0104731489,
   0.007933828048, 0.005787773058,  0.00403327588, 0.002651219722, 0.001607580343,
  0.0008565972093,0.0003444032045,1.288998919e-05,-0.0001964251715,-0.0003387566539,
  -0.0004628362367
};
