/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 22-Jun-2021 18:11:17
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 26
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2021a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 26;
const real32_T B[26] = {
   0.003524016356,  0.00461356109, 0.007320050616,  0.01184476539,  0.01819727197,
    0.02617809363,  0.03538537398,  0.04524564371,  0.05506588891,  0.06410133094,
    0.07163141668,  0.07703518867,   0.0798573941,   0.0798573941,  0.07703518867,
    0.07163141668,  0.06410133094,  0.05506588891,  0.04524564371,  0.03538537398,
    0.02617809363,  0.01819727197,  0.01184476539, 0.007320050616,  0.00461356109,
   0.003524016356
};
