/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 14-Jun-2021 18:09:17
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 26
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2021a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
const int lpf_25_1kHz_length = 26;
const int32_T lpf_25_1kHz_coeffs[26] = {
       7567767,     9907547,    15719689,    25436441,    39078344,    56217028,
      75989510,    97164280,   118253094,   137656565,   153827293,   165431812,
     171492455,   171492455,   165431812,   153827293,   137656565,   118253094,
      97164280,    75989510,    56217028,    39078344,    25436441,    15719689,
       9907547,     7567767
};
